#:schema ../config-schema.json

[inputd.service]
description = "Input Event Daemon"
depends_on = ["syslogd.service"]
part_of = ["base.target"]
options = { exec = "/initrd/services/inputd" }
service = { state-change = "notify", redirect = false }
