[bin.symlink]
type = "symlink"
description = "Symbolic link /bin to /initrd/bin"
part_of = ["base.target"]
link = "/bin"
target = "/initrd/bin"

[etc.symlink]
type = "symlink"
description = "Symbolic link /etc to /initrd/etc"
part_of = ["base.target"]
link = "/etc"
target = "/initrd/etc"
