#:schema ../config-schema.json

[dev.path]
description = "Create dev directory"
options = { path = "/dev" }

[dev-block.path]
description = "Create /dev/block directory"
depends_on = ["dev.path"]
options = { path = "/dev/block" }
