#:schema ../config-schema.json

[pci-discoverer.service]
description = "PCI device discoverer"
depends_on = ["device-manager.service"]
part_of = ["normal.target"]
options = { exec = "/initrd/drivers/pci-daemon" }
