#:schema ../config-schema.json

[virtio.device-template]
template_params = ["device_id", "bus", "dev", "func"]
description = "VirtIO Device [device_id] at [bus]:[dev].[func]"
inherits = "pci.device-template"
inherits_args = { "vendor_id" = "0x1af4" }

[virtio.device-template.options]
driver = "/initrd/drivers/virtiod"
driver_args = [
    "--bus",
    "[bus]",
    "--dev",
    "[dev]",
    "--func",
    "[func]",
    "--mmio-base",
    "0xe0000000",
]

[virtio-net.device-template]
template_params = ["bus", "dev", "func"]
description = "VirtIO Network Device at [bus]:[dev].[func]"
inherits = "virtio.device-template"
inherits_args = { "device_id" = "0x1000" }

[virtio-blk.device-template]
template_params = ["bus", "dev", "func"]
description = "VirtIO Block Device at [bus]:[dev].[func]"
inherits = "virtio.device-template"
inherits_args = { "device_id" = "0x1001" }

[virtio-gpu.device-template]
template_params = ["bus", "dev", "func"]
description = "VirtIO GPU Device at [bus]:[dev].[func]"
inherits = "virtio.device-template"
inherits_args = { "device_id" = "0x1050" }
