#:schema ../config-schema.json

[networkd.service]
description = "Network device manager"
part_of = ["normal.target"]
options = { exec = "/initrd/drivers/networkd" }
service = { state-change = "notify" }

[device-manager.service]
description = "Device manager"
# todo: postprone device discovery to a later stage
depends_on = ["dev.path", "networkd.service"]
part_of = ["normal.target"]
options = { exec = "/initrd/drivers/device-manager" }
service = { state-change = "notify" }

[blockdev-manager.service]
description = "Block device manager"
depends_on = ["dev-block.path", "device-manager.service"]
part_of = ["normal.target"]
options = { exec = "/initrd/drivers/blockdev-manager" }
service = { state-change = "notify" }

[ext4fs.service]
description = "Ext4 file system driver"
depends_on = ["blockdev-manager.service"]
options = { exec = "/initrd/drivers/ext4fs" }
service = { state-change = "notify" }
