[sys.path]
type = "path"
description = "Create SysFS directory"
options = { path = "/sys" }

[sys.mount]
type = "mount"
description = "Mount SysFS"
depends_on = ["sys.path"]
part_of = ["base.target"]
options = { mount_point = "/sys", fs_type = "sysfs", options = "defaults", device = "none" }
