[syslogd.service]
type = "service"
description = "System log daemon"
depends_on = ["sys.mount"]
part_of = ["normal.target"]
options = { exec = "/initrd/programs/syslogd" }
service = { state-change = "notify" }
