[test-true.service]
type = "service"
description = "Test Service - True"
exec = "/initrd/programs/true"

[test-false.service]
type = "service"
description = "Test Service - False"
exec = "/initrd/programs/false"
