[virtio.device-template]
type = "device"
template_args = ["type"]
description = "VirtIO $type Device"
[virtio.device-template.options]
driver = "/initrd/drivers/virtiod"
driver_args = [
    "--vendor_id",
    "$vendor_id",
    "--device_id",
    "$device_id",
    "--location",
    "$location",
    "--mmio_base",
    "$mmio_base",
    "--device_type",
    "$type",
]
