# MOS Service Configuration

# Include all files in bits/
include = ["bits/*.toml"]

# The default target to boot into
default_target = "normal.target"

[normal.target]
description = "Normal System"
depends_on = ["base.target"]
